name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build_test_job:
    name: 'Build and test job'
    runs-on: ubuntu-latest
    steps:

    - name: 'Checking out repo code'
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

    - name: 'Validate build'
      working-directory: ./build_and_deploy
      run: |
        npm install
        npm run build
    - name: 'Run tests'
      working-directory: ./build_and_deploy
      run: |
        npm run test
