name: Test

on:
  push:
    branches:
      - feature/federated-identity-support
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Create Dummuy Files
        run: |
          touch TemplateForWorkspace.json
          touch TemplateParametersForWorkspace.json

      - name: Test Action
        uses: ./
        with:
          TargetWorkspaceName: myworkspace
          TemplateFile: "./TemplateForWorkspace.json"
          ParametersFile: "./TemplateParametersForWorkspace.json"
          environment: "Azure Public"
          resourceGroup: "myresourcegroup"
          clientId: ${{ vars.AZURE_CLIENT_ID }}
          federatedIdentity: true
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          tenantId: ${{ vars.AZURE_TENANT_ID }}
          operation: "deploy"
